In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(2,3) + 10

In [3]:
a

array([[10, 11, 12],
       [13, 14, 15]])

In [4]:
np.argmax(a)

5

In [5]:
np.argmax(a, axis=0)

array([1, 1, 1], dtype=int64)

In [6]:
np.argmax(a, axis=1)

array([2, 2], dtype=int64)

In [7]:
b = np.arange(6)

In [8]:
b[1] = 5

In [9]:
b

array([0, 5, 2, 3, 4, 5])

In [10]:
np.argmax(b)

1

In [11]:
x = np.arange(24).reshape((2, 3, 4))

In [12]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
res = np.argmax(x, axis=1, keepdims=True)

In [14]:
res

array([[[2, 2, 2, 2]],

       [[2, 2, 2, 2]]], dtype=int64)

In [15]:
res.shape

(2, 1, 4)